apiVersion: apps/v1
kind: Deployment
metadata:
  name: antrea-toolbox-deployment
  namespace: lfx-mentorship
  labels:
    name: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: toolbox
  template:
    metadata:
      labels:
        name: toolbox
    spec:
      containers:
      - name: toolbox
        image: antrea/toolbox:1.4
